/*
 * Copyright 2011 Free Software Foundation, Inc.
 *
 * This file was generated by gr_modtool, a tool from the GNU Radio framework
 * This file is a part of gr-circular_conv
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

#ifndef INCLUDED_CIRCULAR_CONV_API_H
#define INCLUDED_CIRCULAR_CONV_API_H

#include <gnuradio/attributes.h>

#ifdef gnuradio_circular_conv_EXPORTS
#define CIRCULAR_CONV_API __GR_ATTR_EXPORT
#else
#define CIRCULAR_CONV_API __GR_ATTR_IMPORT
#endif

#endif /* INCLUDED_CIRCULAR_CONV_API_H */
